### ISSUE TITLE
Endomondo limiting gpx files to 10MB

### ISSUE THREAD

**Issue by mirelon** [conoro/runkeeper2endomondo#1]
Upload form on endomondo web says: "Choose a file on your computer and press upload to display the workouts contained in the file. Valid file formats are .gpx, .tcx and .fit with a maximum file size of 10 MB."

My created endomondo.gpx has file size 22MB. Consider an option to split files to match the endomondo limits...

It is just a feature request to automatically create endomondo1.gpx, endomondo2.gpx, and so on...

**Comment by conoro** [comment]
Merged.
